name: CI RSpec Test

on: [push, pull_request]

jobs:
  build:
    name: >-
      Mongoid Test with: - Ruby ${{ matrix.ruby }} - MongoDB ${{ matrix.mongodb }} - Gemfile ${{ matrix.gemfile }})
    env:
      CI: true
      TESTOPTS: "-v"
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1"]
        gemfile: ["monogid_3", "mongoid_4", "mongoid_5", "mongoid_6", "mongoid_7", "mongoid_8", "mongoid_9"]
        mongodb: ["3.6", "4.0", "4.2", "4.3", "4.4", "5.0", "6.0", "7.0"]
        exclude:
          # Exclude incompatible combinations
          - { ruby: "2.6", gemfile: "mongoid_9" }
          - { ruby: "2.6", gemfile: "mongoid_7", mongodb: "4.0" }
          - { ruby: "2.6", gemfile: "mongoid_7", mongodb: "4.2" }
          - { ruby: "2.6", gemfile: "mongoid_7", mongodb: "4.4" }
          - { ruby: "2.6", gemfile: "mongoid_7", mongodb: "5.0" }
          - { ruby: "2.6", gemfile: "mongoid_7", mongodb: "6.0" }
          - { ruby: "2.6", gemfile: "mongoid_7", mongodb: "7.0" }
          - { ruby: "2.6", gemfile: "mongoid_8", mongodb: "4.0" }
          - { ruby: "2.6", gemfile: "mongoid_8", mongodb: "4.2" }
          - { ruby: "2.6", gemfile: "mongoid_8", mongodb: "4.4" }
          - { ruby: "2.6", gemfile: "mongoid_8", mongodb: "5.0" }
          - { ruby: "2.6", gemfile: "mongoid_8", mongodb: "6.0" }
          - { ruby: "2.6", gemfile: "mongoid_8", mongodb: "7.0" }
          - { ruby: "3.1", gemfile: "mongoid_3" }
          - { ruby: "3.1", gemfile: "mongoid_4" }
          - { ruby: "3.1", gemfile: "mongoid_5" }
    steps:
      - name: Set up MongoDB ${{ matrix.mongodb }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: '2'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake